# Generated by Django 6.0.6 on 2026-07-01 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='🎮', max_length=10)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('developer', models.CharField(default='Obsidian Originals', max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_editors_choice', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('plays', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=4.5)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('color_from', models.CharField(default='#7C5CFF', max_length=20)),
                ('color_to', models.CharField(default='#00CFFF', max_length=20)),
                ('thumbnail', models.CharField(blank=True, help_text='Path relative to games_static, e.g. nightCityDivination/assets/banner.webp', max_length=500)),
                ('banner', models.CharField(blank=True, max_length=500)),
                ('game_folder', models.CharField(help_text='Path relative to games_static root, e.g. nightCityDivination', max_length=300)),
                ('game_entry', models.CharField(default='index.html', max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='store.genre')),
            ],
            options={
                'ordering': ['-is_featured', '-plays'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('game', 'user')},
            },
        ),
    ]
